repos:
- repo: local
  hooks:
    - id: front
      name: Frontend
      entry: bash -c "cd front && poetry run ruff check --fix && poetry run ruff format && poetry run python -m pytest"
      language: system
      types: [python]
    
    - id: back
      name: Backend
      entry: bash -c "cd backend && poetry run ruff check --fix && poetry run ruff format && poetry run python -m pytest"
      language: system
      types: [python]

    - id: azureml
      name: AzureML
      entry: bash -c "cd azureml && poetry run ruff check --fix && poetry run ruff format && poetry run python -m pytest"
      language: system
      types: [python]

- repo: https://github.com/Yelp/detect-secrets
  rev: v1.5.0
  hooks:
  -   id: detect-secrets
      args: ['--baseline', '.secrets.baseline']
      exclude: package.lock.json