repos:
- repo: local
  hooks:
    - id: front
      name: Frontend
      entry: cd front && poetry run ruff check && poetry run python -m pytest
      language: system
      types: [python]
    
    - id: back
      name: Backend
      entry: cd backend && poetry run ruff check && poetry run python -m pytest
      language: system
      types: [python]

