version: '3'

services:
  chroma:
    image: chromadb/chroma:latest
    ports:
      - 8000:8000

  backend:
    build: ./backend
    volumes:
      - ./backend:/backend
    depends_on:
      - chroma
    ports:
      - 8888:8888
    environment:
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
      - CHROMA_HOST=chroma

  front:
    build: ./front
    volumes:
      - ./front:/front
    depends_on:
      - backend
    ports:
      - 8501:8501
    environment:
      - BACKEND_HOST=http://backend
