
services:
  - name: front
    type: web
    runtime: docker
    repo: https://github.com/ruaultadrien/conception
    dockerfilePath: front/Dockerfile
    dockerContext: front
    plan: free
    envVars:
      - key: BACKEND_URL
        fromService:
          name: back
          type: web
          property: host

  - name: back
    type: web
    runtime: docker
    repo: https://github.com/ruaultadrien/conception
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    plan: free

  - name: chroma
    type: web
    runtime: docker
    image: chromadb/chroma:latest
    plan: free