name: CI AzureML

on:
  push:
    branches: [ main ]
    paths:
      - 'azureml/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'azureml/**'
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        run: az acr login --name ${{ secrets.REGISTRY_SERVER }}

      #- name: Docker login to Azure Container Registry
        #uses: docker/login-action@v3
        #with:
          #registry: ${{ secrets.REGISTRY_SERVER }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: azureml
          file: azureml/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_SERVER }}/azureml:latest
          cache-from: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/azureml:latest
          cache-to: type=inline


      - name: Create an AzureML environment from the Docker image
        run: |
          az extension add -n ml
          az ml environment create \
            --name azureml-environment \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --workspace-name ${{ secrets.WORKSPACE_NAME }} \
            --docker ${{ secrets.REGISTRY_SERVER }}/azureml:latest

  