name: CI AzureML

on:
  push:
    branches: [ main ]
    paths:
      - 'azureml/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'azureml/**'

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker login to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: azureml
          file: azureml/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_SERVER }}/azureml:latest
          cache-from: type=registry,ref=${{ secrets.REGISTRY_SERVER }}/azureml:latest
          cache-to: type=inline

      - name: Set up Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Create an AzureML environment from the Docker image
        run: |
          az ml environment create --name azureml-environment --docker ${{ secrets.REGISTRY_SERVER }}/azureml:latest

  