name: CI AzureML

on:
  push:
    branches: [ main, dev ]
    paths:
      - 'azureml/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'azureml/**'

jobs:
  push-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Docker login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
