name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd front
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        shell: bash
      
      - name: Check Python Style with visiumlint
        run: |
          cd front
          poetry run visiumlint
        shell: bash
      
      - name: Run tests
        run: |
          cd front
          poetry run python -m pytest
        shell: bash
  
  ci-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        shell: bash
      
      - name: Check Python Style with visiumlint
        run: |
          cd backend
          poetry run visiumlint
        shell: bash
      
      - name: Run tests
        run: |
          cd backend
          poetry run python -m pytest
        shell: bash