name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd front
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        shell: bash
      
      - name: Check Python Style
        run: |
          cd front
          poetry run ruff check
        shell: bash
      
      - name: Run tests
        run: |
          cd front
          poetry run python -m pytest
        shell: bash
  
  docker-build-front:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: front
          file: front/Dockerfile
          push: false
  
  ci-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
        shell: bash
      
      - name: Check Python Style
        run: |
          cd backend
          poetry run ruff check
        shell: bash
      
      - name: Run tests
        run: |
          cd backend
          poetry run python -m pytest
        shell: bash
  
  docker-build-back:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: backend
          file: backend/Dockerfile
          push: false